[shell]

program = "ssh.exe"

args = ["-X", "chielin@10.192.101.207"]





[font]

size = 12

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }



[cursor]

style = { shape = "Beam", blinking = "Always" }





# The following colors setting is Wez

[colors.primary]

foreground= "#B3B3B3"

background = "#000000"



[colors.normal]

black= "#000000"

blue= "#5555CC"

cyan= "#7ACACA"

green= "#55CC55"

magenta = "#CC55CC"

red= "#CC5555"

white= "#CCCCCC"

yellow= "#CDCD55"



[colors.bright]

black= "#555555"

blue= "#5555FF"

cyan= "#55FFFF"

green= "#55FF55"

magenta = "#FF55FF"

red= "#FF5555"

white= "#FFFFFF"

yellow= "#FFFF55"



[selection]

save_to_clipboard = true
